enableGlobalCache: true

packageExtensions:
  # fix https://github.com/facebook/create-react-app/issues/11793
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  # fix https://github.com/facebook/create-react-app/issues/10718
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
